#! /usr/bin/env python
Import( 'env' )

obj=env.qt4obj('shlib', env)
env.Add_define('PACKAGE')
env.Add_define('SCIM_VERSION')
env.Add_define('SCIM_ICONDIR')

obj.target='libqscim'
obj.source="""
plugin.cpp
qsciminputcontext.cpp
"""
#obj.cxxflags='-DQT_THREAD_SUPPORT'
#obj.libs='QtOpenGL_debug QtGui_debug png SM ICE Xi Xrender Xrandr Xcursor Xinerama freetype fontconfig Xext X11 m QtCore_debug z dl GLU GL pthread'
obj.cxxflags=env['SCIM_CFLAGS']
obj.linkflags=env['SCIM_X11_LIBS'] #env['SCIM_LIBS']
#env.QT4addflags_link(env['SCIM_LIBS'])
#obj.includes='#/ ./'
obj.instdir=env.join(env['QTLIBPATH'], 'plugins', 'inputmethods')
obj.execute()


## This shows how to add custom link flags to the program
#env.QT4addflags_link(['-export-dynamic'])

#############################
## Data to install

## The ui.rc file and the tips go into datadir/appname/
#env.QT4install( 'QT4DATA', 'test1', 'test1ui.rc' )
#env.QT4install( 'QT4DATA', 'test1', 'tips' )

## The kcfg file is installed in a global kcfg directory
#env.QT4install( 'QT4KCFG', '', 'test1.kcfg' )

## Warning : there is a difference between the normal destop file used for the menu
##     and the servicetype desktop file, so they go in different directories
##     you will find more information in 'test3'
#env.QT4install( 'QT4MENU', 'Utilities', 'test1.desktop')

## Use this when you need to install a mimetype file
#env.QT4install( 'QT4MIME', 'application', 'x-test1.desktop' )

