all:
	@./scons -Q

# it is also possible to use
# @./scons -Q -j4

install:
	@./scons -Q install

clean:
	@./scons -Q -c

uninstall:
	@./scons -Q -c install

dist:
	@./scons -Q dist

distclean:
	@./scons -Q -c
	rm -rf cache/
