#! /usr/bin/env python

Import( 'env' )

scimlauncher_sources='scimlauncher.cpp'
plugin_desktop_file='skimplugin_scim.desktop'
env.SKIMPLUGIN('skimplugin_scim', scimlauncher_sources, plugin_desktop_file)