#! /usr/bin/env python

Import( 'env' )

def FormatPoFiles(env, target, source):
	comp='$MSGFMT --statistics $source -o $target'
	return env.Execute(comp)
	
env['BUILDERS']['FormatPoFiles']=Builder(action=env.Action(FormatPoFiles),suffix='.gmo',src_suffix='.po')

import glob
import SCons
import string
def SKIMlang(lenv, folder, appname):
		""" Process translations (.po files) in a po/ dir """
		transfiles = glob.glob(folder+'/*.po')
		for lang in transfiles:
			result = lenv.Transfiles(lang)
			country = SCons.Util.splitext(result[0].name)[0]
			if string.find(lang, 'desktop') == -1:
				dir=env.getInstDirForResType('KDELOCALE')
                                lenv.bksys_install(dir+'/'+country+'/LC_MESSAGES/', result, destfile=appname+'.mo')

from SCons.Script.SConscript import SConsEnvironment
SConsEnvironment.SKIMlang = SKIMlang

env.SKIMlang('./',env['PACKAGE'])
