#! /usr/bin/env python
## This script demonstrates how to build and install
## a complex kde program depending on several
## shared libraries with scons
##
## Thomas Nagy, 2004, 2005
## This file can be reused freely for any project (see COPYING)

Import( 'env' )

kconfig=env.Copy()

kconfig_sources='scim_kconfig_config.cpp'

kconfig.KDEaddpaths_includes( "#/ #/utils" )
kconfig.KDEaddlibs( "qt-mt kdecore kdeui kutils" )

kconfig.SCIMshlib( 'SCIMCONFIGLIB', 'kconfig', kconfig_sources, 1, "#/utils/libscim-kdeutils.la")
